FROM openjdk:16-alpine3.13

WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN chmod 765 ./mvnw
RUN ./mvnw dependency:go-offline

COPY src ./src
EXPOSE $PORT
CMD  ./mvnw spring-boot:run -Dspring-boot.run.arguments=--server.port=$PORT
